import { Request, Response, NextFunction } from 'express';
import jwt from 'jsonwebtoken';

import { AppError } from '../utils/AppError';
import { HTTP, ErrorCode } from '../utils/constants';

// ─── Extend Express's Request type to carry the authenticated user ────────────
//
// TypeScript's Express typings don't include a `user` property on Request out
// of the box. We augment the global Express namespace here so that req.user is
// available in any controller file without needing a cast.

declare global {
  namespace Express {
    interface Request {
      user?: AuthenticatedUser;
    }
  }
}

// The shape of the data we store inside the JWT payload.
// Keep this lean — only what every module will routinely need.
// Never put sensitive data (password hash, full employee record) in the token.
export interface AuthenticatedUser {
  id: number;
  email: string;
  permissions: string[];
  departmentId: number | null;
  organizationId: number;
}

// The shape of what jwt.verify returns for our tokens.
// jwt.verify returns `string | JwtPayload` (any in older typings), so we
// define a precise type and cast to it after verifying the fields are present.
interface JwtPayload {
  id: number;
  email: string;
  permissions: string[];
  departmentId: number | null;
  organizationId: number;
  iat: number;
  exp: number;
}

// ─── requireAuth ──────────────────────────────────────────────────────────────
//
// Verifies the JWT from the Authorization: Bearer <token> header.
// On success: attaches req.user and calls next().
// On failure: throws AppError(401) — the global handler returns the JSON response.
//
// This middleware must be the first middleware on any protected route.
// Routes that are intentionally public (e.g. /health, /auth/login) do NOT use this.

export function requireAuth(req: Request, _res: Response, next: NextFunction): void {
  try {
    const authHeader = req.headers.authorization;

    if (!authHeader || !authHeader.startsWith('Bearer ')) {
      throw new AppError(
        'Authentication required. Provide a valid Bearer token.',
        HTTP.UNAUTHORIZED,
        ErrorCode.UNAUTHORIZED,
      );
    }

    const token = authHeader.slice(7); // Remove "Bearer " prefix
    const secret = process.env.JWT_SECRET;

    if (!secret) {
      // This is a server configuration error, not a client error.
      // Log it as a hard error and return a generic 500.
      console.error('[FATAL] JWT_SECRET is not set in environment variables.');
      throw new AppError(
        'Server configuration error.',
        HTTP.SERVER_ERROR,
        ErrorCode.SERVER_ERROR,
      );
    }

    // jwt.verify throws if the token is expired, malformed, or has a bad signature.
    // We catch those below and convert to an AppError.
    const decoded = jwt.verify(token, secret) as JwtPayload;

    // Validate that the payload contains the fields we expect.
    // This guards against tokens generated by a different system or an old version.
    if (!decoded.id || !decoded.email || !decoded.permissions || !decoded.organizationId) {
      throw new AppError('Token payload is invalid.', HTTP.UNAUTHORIZED, ErrorCode.UNAUTHORIZED);
    }

    req.user = {
      id: decoded.id,
      email: decoded.email,
      permissions: decoded.permissions,
      departmentId: decoded.departmentId,
      organizationId: decoded.organizationId,
    };

    next();
  } catch (err) {
    // Re-throw AppErrors as-is (they already have the right status/code).
    if (err instanceof AppError) {
      next(err);
      return;
    }

    // JsonWebTokenError and TokenExpiredError both extend Error.
    // We convert them to an AppError so the global handler formats them correctly.
    if (err instanceof Error) {
      const message =
        err.name === 'TokenExpiredError'
          ? 'Your session has expired. Please log in again.'
          : 'Invalid authentication token.';

      next(new AppError(message, HTTP.UNAUTHORIZED, ErrorCode.UNAUTHORIZED));
      return;
    }

    next(new AppError('Authentication failed.', HTTP.UNAUTHORIZED, ErrorCode.UNAUTHORIZED));
  }
}

// ─── requirePermission ────────────────────────────────────────────────────────
//
// Returns a middleware that checks whether req.user.permissions includes at least
// one of the allowed permissions.
// Must be used AFTER requireAuth on the same route.
//
// Usage:
//   router.post('/promote', requireAuth, requirePermission([Permission.MANAGE_ORGANIZATION]), promoteEmployee);
//

export function requirePermission(allowedPermissions: string[]) {
  return (req: Request, _res: Response, next: NextFunction): void => {
    if (!req.user) {
      next(
        new AppError(
          'requirePermission called without requireAuth. Check route middleware order.',
          HTTP.SERVER_ERROR,
          ErrorCode.SERVER_ERROR,
        ),
      );
      return;
    }

    // Admins usually have all permissions, but for clarity, the user object
    // should just have the permissions array populated from the DB.
    const hasPermission = allowedPermissions.some(perm => req.user!.permissions.includes(perm));

    if (!hasPermission) {
      next(
        new AppError(
          'You do not have permission to perform this action.',
          HTTP.FORBIDDEN,
          ErrorCode.FORBIDDEN,
        ),
      );
      return;
    }

    next();
  };
}
